### ISSUE TITLE
can't install with v0.6.6 due to jshint

### ISSUE THREAD

**Issue by orlin** [fat/smoosh#17]
This is [jshint's issue 404](https://github.com/jshint/jshint/issues/404) impacting you.  It installs ok with with v0.4.12.  But after switching back to v0.6.6 I get UNMET DEPENDENCY with `npm ls`:

```
─┬ smoosh@0.3.1 
│ ├── asciimo@0.3.1 
│ ├── colors@0.6.0-1 
│ ├── gzip@0.1.0 
│ ├── UNMET DEPENDENCY jshint >= 0.1.4
│ ├── rimraf@1.0.9 
│ └── sqwish@0.2.0
```

Better than smoosh being unmet.  I won't be smooshing just yet, because I'm in a dirty branch state.  If smoosh doesn't have to run jshint, I guess I'll be ok.

**Comment by ded** [comment]
yep. this shouldn't really be smooshes fault. i had to install node v0.4.12 to smoosh all my open source work. it's a bum deal, we know.
