### ISSUE TITLE
Smoosh outputs errors based on concatenated file and not individual files

### ISSUE THREAD

**Issue by ded** [fat/smoosh#2]
Just came across this. When Smoosh finds lint errors (from JS Hint) it outputs line numbers based on the concatenated file which makes it harder to track down where (which file) the errors are.

**Comment by ded** [comment]
^ I just voted up that comment. Awesome.

**Comment by fat** [comment]
fixed... but only because it was so highly voted up

**Comment by fat** [comment]
closing.
