### ISSUE TITLE
Exclude .gitignore from npm-package?

### ISSUE THREAD

**Issue by voxpelli** [fat/smoosh#7]
I installed this module locally through npm and thought I should commit it together with my project in my own git-repo. Unfortunately there's a gitignore-file in the smoosh-package that excludes smoosh's dependencies from any git-repo so it's not possible to commit a local package for npm into a git-repo as the dependencies of smoosh won't be fulfilled.

**Comment by fat** [comment]
I just removed that from the git_ignore and republished -- should just be able to update and it will work now!

**Comment by voxpelli** [comment]
Thanks for a quick fix!

**Comment by fat** [comment]
np
