### ISSUE TITLE
Don't remove the DIST_DIR from options

### ISSUE THREAD

**Issue by voxpelli** [fat/smoosh#9]
When sending in a config object to Smoosh it seems that Smoosh removes the DIST_DIR from it somewhere. This has the result that if the same config object is used to execute two Smoosh calls then the second Smoosh call will not get the configured DIST_DIR.

Haven't had time to look where this happens in the code so I've no patch for you. Reporting anyway so that you're aware of the issue.

**Comment by danro** [comment]
+1 also ran into this today.
